In [9]:
%matplotlib widget

In [1]:
congress116 = "https://voteview.com/static/data/out/members/HS116_members.json"
congress116_file = "HS116_members.json"

In [2]:
import pandas as pd

In [4]:
df = pd.read_json(congress116_file)
df.head()

,congress,chamber,icpsr,state_icpsr,district_code,state_abbrev,party_code,occupancy,last_means,bioname,...,died,nominate_dim1,nominate_dim2,nominate_log_likelihood,nominate_geo_mean_probability,nominate_number_of_votes,nominate_number_of_errors,conditional,nokken_poole_dim1,nokken_poole_dim2
0,116,House,20301,41,3,AL,200,,,"ROGERS, Mike Dennis",...,NaN,0.353,0.459,-157.12696,0.78556,651,64,NaN,0.520,0.347
1,116,House,21102,41,7,AL,100,,,"SEWELL, Terri",...,NaN,-0.391,0.402,-26.01682,0.96146,662,11,NaN,-0.435,0.395
2,116,House,21192,41,2,AL,200,,,"ROBY, Martha",...,NaN,0.361,0.656,-86.62113,0.87433,645,30,NaN,0.341,0.673
3,116,House,21193,41,5,AL,200,,,"BROOKS, Mo",...,NaN,0.647,-0.446,-124.80360,0.83187,678,50,NaN,0.786,-0.368
4,116,House,21376,41,1,AL,200,,,"BYRNE, Bradley",...,NaN,0.611,0.244,-101.01760,0.84830,614,40,NaN,0.707,0.167

In [10]:
df.plot(kind="scatter", x="nominate_dim1", y="nominate_dim2")

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …